// Command compare runs every scenario through two detectors and writes a
// markdown table:
//
//   - naive: fixed spec-sheet limits per sensor (demo/equipment.yaml "spec"),
//     the way most render-farm monitoring is configured today;
//   - adaptive: the pipeline's windowed EWMA / z-score detector.
//
// It is about the deterministic detection layer only - no model involved.
// With -bedrock it also sends each flagged anomaly through the real explain
// step and checks the severity against demo/expected.json.
//
//	go run ./compare                       # offline
//	go run ./compare -out compare/RESULTS.md
//	go run ./compare -bedrock -profile demos-admin -out compare/RESULTS.md
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"os"
	"slices"
	"sort"
	"strings"

	northfen "github.com/marianina8/northfen-telemetry-pipeline"
	"github.com/marianina8/northfen-telemetry-pipeline/internal/config"
	"github.com/marianina8/northfen-telemetry-pipeline/internal/detect"
	"github.com/marianina8/northfen-telemetry-pipeline/internal/dispatch"
	"github.com/marianina8/northfen-telemetry-pipeline/internal/explain"
	"github.com/marianina8/northfen-telemetry-pipeline/internal/pipeline"
	"github.com/marianina8/northfen-telemetry-pipeline/internal/sim"
	"github.com/marianina8/northfen-telemetry-pipeline/internal/store"
	"github.com/marianina8/northfen-telemetry-pipeline/internal/telemetry"
)

type expected struct {
	ShouldFlag       bool     `json:"should_flag"`
	IntendedSeverity []string `json:"intended_severity"`
	MustMention      bool     `json:"must_mention_correlation"`
	Alerts           []struct {
		Kind    string   `json:"kind"`
		Sensors []string `json:"sensors"`
	} `json:"alerts"`
}

// naive flags a sensor the first time a reading leaves its spec limits.
// Missing readings are simply skipped (a fixed limit can't see them).
func naive(cat *sim.Catalog, rs []telemetry.Reading) map[string]int {
	first := map[string]int{}
	for _, r := range rs {
		eq, _ := cat.Tool(r.EquipmentID)
		sn, _ := eq.Sensor(r.SensorID)
		if r.Value == nil {
			continue
		}
		if v := *r.Value; v < sn.Spec.Lo || v > sn.Spec.Hi {
			if _, ok := first[r.SensorID]; !ok {
				first[r.SensorID] = r.Tick
			}
		}
	}
	return first
}

func adaptive(cfg *config.Config, rs []telemetry.Reading) (map[string]int, string) {
	first := map[string]int{}
	kind := ""
	for _, s := range detect.ScoreAll(cfg.Detector, rs, false) {
		if len(s.Flags) > 0 {
			first[s.SensorID] = s.Flags[0].Tick
			kind = s.Flags[0].Kind
		}
	}
	return first, kind
}

func describe(m map[string]int) string {
	if len(m) == 0 {
		return "no flag"
	}
	var ks []string
	for k := range m {
		ks = append(ks, k)
	}
	sort.Slice(ks, func(i, j int) bool { return m[ks[i]] < m[ks[j]] })
	var parts []string
	for _, k := range ks {
		parts = append(parts, fmt.Sprintf("%s @%d", k, m[k]))
	}
	return strings.Join(parts, ", ")
}

func verdict(flagged, should bool) string {
	switch {
	case flagged && should:
		return "✅ caught"
	case !flagged && !should:
		return "✅ quiet"
	case flagged:
		return "❌ false alarm"
	}
	return "❌ missed"
}

func main() {
	out := flag.String("out", "", "write markdown here (default stdout)")
	bedrock := flag.Bool("bedrock", false, "also run flagged anomalies through Amazon Bedrock")
	profile := flag.String("profile", "", "AWS profile for Bedrock")
	flag.Parse()
	ctx := context.Background()
	cfg := config.Default()
	cat := sim.MustCatalog()
	b, _ := fs.ReadFile(northfen.Demo, "demo/expected.json")
	var doc struct {
		Scenarios map[string]expected `json:"scenarios"`
	}
	if err := json.Unmarshal(b, &doc); err != nil {
		fail(err)
	}

	var model explain.Model
	if *bedrock {
		cfg.Explain.Provider = "bedrock"
		m, err := explain.New(ctx, cfg, *profile)
		if err != nil {
			fail(err)
		}
		model = m
	}

	var w io.Writer = os.Stdout
	if *out != "" {
		f, err := os.Create(*out)
		if err != nil {
			fail(err)
		}
		defer f.Close()
		w = f
	}
	fmt.Fprintln(w, "# Naive fixed limits vs. adaptive windowed detection")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Same synthetic scenarios, two deterministic detectors, no model involved. **Naive** uses the fixed spec-sheet")
	fmt.Fprintln(w, "limits in `demo/equipment.yaml` (how most render-farm monitoring is configured). **Adaptive** is the pipeline's detector:")
	fmt.Fprintln(w, "it learns each metric's own normal, then applies EWMA/z-score rules plus stuck and dropout checks. Cells show which metric")
	fmt.Fprintln(w, "flagged and at which tick. Generated by `go run ./compare`.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "| Scenario | Should flag? | Naive fixed limits | | Adaptive detector | |")
	fmt.Fprintln(w, "|---|---|---|---|---|---|")
	var nOK, aOK, n int
	var bedrockRows []string
	for _, sc := range cat.Scenarios {
		e := doc.Scenarios[sc.File]
		rs, _ := sim.Generate(cat, sc, sim.Options{})
		nf := naive(cat, rs)
		af, kind := adaptive(cfg, rs)
		nv, av := verdict(len(nf) > 0, e.ShouldFlag), verdict(len(af) > 0, e.ShouldFlag)
		n++
		if strings.HasPrefix(nv, "✅") {
			nOK++
		}
		if strings.HasPrefix(av, "✅") {
			aOK++
		}
		should := "no"
		if e.ShouldFlag {
			should = "yes"
			if len(e.Alerts) > 0 && e.Alerts[0].Kind == "sensor_fault" {
				should = "yes (sensor fault)"
			}
		}
		adesc := describe(af)
		if kind == detect.KindSensorFault {
			adesc += " (sensor fault)"
		}
		fmt.Fprintf(w, "| `%s` | %s | %s | %s | %s | %s |\n", sc.File, should, describe(nf), nv, adesc, av)

		if model != nil && e.ShouldFlag && len(e.IntendedSeverity) > 0 {
			svc := &pipeline.Service{Cfg: cfg, Cat: cat, Store: store.NewMem(), Model: model, Sink: &dispatch.LogSink{}}
			svc.SeedHistory(ctx)
			_, as, err := svc.RunBatch(ctx, pipeline.RunRequest{Scenario: sc.Name, RunID: "R1", TickSeconds: 1}, 100)
			if err != nil {
				fail(err)
			}
			for _, a := range as {
				row := fmt.Sprintf("| `%s` | %s | ", sc.File, a.Explain)
				if ex := a.Explanation; ex != nil && a.Explain == store.ExplainDone {
					ok := slices.Contains(e.IntendedSeverity, ex.Severity)
					corr := ""
					if e.MustMention {
						corr = " · mentions correlation: " + yesno(mentionsCorrelation(ex.Explanation))
					}
					row += fmt.Sprintf("%s (%s) | %.2f | %s | %s | %s%s |", ex.Severity, yesno(ok), ex.Confidence, strings.Join(ex.LikelyCauses, ", "),
						a.Decision.Action, strings.ReplaceAll(ex.Explanation, "|", "/"), corr)
				} else {
					row += fmt.Sprintf("- | - | - | %s | %s |", a.Decision.Action, a.ExplainErr)
				}
				bedrockRows = append(bedrockRows, row)
			}
		}
	}
	fmt.Fprintf(w, "\n**Naive: %d/%d correct. Adaptive: %d/%d correct.**\n\n", nOK, n, aOK, n)
	fmt.Fprintln(w, "Where they differ:")
	fmt.Fprintln(w, "- **Driver drift** (`04`): node12's frame time creeps up after its GPU driver update but never reaches the 14 min/frame alert limit, so the fixed limit never fires. The adaptive baseline moving 4σ from where it started does.")
	fmt.Fprintln(w, "- **Bursty but healthy** (`06`): the expanded compositing pool mixes light and very heavy shots, so its frame time crosses the fixed limit within minutes even though nothing is wrong. That's a false alarm that trains wranglers to ignore alerts. The adaptive detector learns this pool's own swing.")
	fmt.Fprintln(w, "- **Frozen license monitor / silent node** (`07`, `08`): a frozen or silent metric looks \"within limits\" to a fixed threshold. The adaptive detector treats both as monitoring faults.")
	fmt.Fprintln(w, "- **Storage slowdown** (`10`): both catch it, but look at the order. The fixed limits page about two slow nodes first; NAS latency only crosses its own limit at tick 116, about 40 ticks later, so the first page points at the nodes. The adaptive detector flags storage latency first (tick 67) and both nodes within 8 ticks, and the pipeline groups all three into one alert whose diagnosis points at shared storage.")
	fmt.Fprintln(w, "- **Deadline Cloud replay** (`11`): both catch it. node12's frames (resampled from a Deadline Cloud export) get about 25% slower, which is enough to cross the fixed limit too. Detection isn't the hard part here; what matters is what happens next: the diagnosis names one node rather than shared storage, and a lone slow node opens a ticket instead of paging someone at 3am.")
	fmt.Fprintln(w, "- **Threshold boundary** (`09`) isn't a fair fight. It's a hand-built fixture that pins the adaptive detector's exact z = 3.0 cutoff, well inside the alert limits by design. It's included so the table covers every fixture.")
	if len(bedrockRows) > 0 {
		fmt.Fprintf(w, "\n## Explain step on Amazon Bedrock (`%s`)\n\n", model.Name())
		fmt.Fprintln(w, "| Scenario | Explain | Severity (in intended band?) | Confidence | Likely causes | Action | Explanation |")
		fmt.Fprintln(w, "|---|---|---|---|---|---|---|")
		for _, r := range bedrockRows {
			fmt.Fprintln(w, r)
		}
	}
}

func mentionsCorrelation(s string) bool {
	s = strings.ToLower(s)
	for _, w := range []string{"together", "correlat", "simultaneous", "all three", "both", "in tandem", "alongside"} {
		if strings.Contains(s, w) {
			return true
		}
	}
	return false
}

func yesno(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "compare:", err)
	os.Exit(1)
}
